<a href="https://colab.research.google.com/github/kenzalber/DS1002/blob/main/07_More_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More pandas exercises

Create a Colab notebook. Complete the tasks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

1.  Load the following dataset into Colab and perform the requested operations in code.

 Source: https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv

In [98]:
# Load pandas and the data

import pandas as pd
ride_sharing = pd.read_csv("ride_sharing.csv")

In [99]:
# show how many rows and columns are in this dataset

print(ride_sharing.shape)

#There are 25760 rows and 10 columns

(25760, 10)

In [100]:
# The first column, "duration" is seen as a string.
# Using two snippets of code, clean this column up so that
# is now an integer (int64)

ride_sharing['duration'] = ride_sharing['duration'].str.strip('minutes')
ride_sharing['duration'] = ride_sharing['duration'].astype(int)

In [101]:
# Now display the datatypes in the updated dataframe

print(ride_sharing.dtypes)

duration            int64
station_A_id        int64
station_A_name     object
station_B_id        int64
station_B_name     object
bike_id             int64
user_type           int64
user_birth_year     int64
user_gender        object
tire_size           int64
dtype: object

In [102]:
# Show the min and max values of ride durations (the shortest and longest rides)
# Hint: If 'df' is the name of your dataframe, simply specify the column name
# and then append the .min() or .max() methods.

max = ride_sharing['duration'].max()
print("Max duration = " + str(max))
min = ride_sharing['duration'].min()
print("Min duration = " + str(min))

Max duration = 1372
Min duration = 1

In [103]:
# Create a new dataframe object and populate it with rides that are 60 minutes or less.
# Hint: Use the .query() method for the dataframe that we used in class.

shortened_rides = ride_sharing.query('duration <= 60')

In [104]:
# Now show both the min and max values of the duration column for your new dataset.
max = shortened_rides['duration'].max()
print("Max duration = " + str(max))
min = shortened_rides['duration'].min()
print("Min duration = " + str(min))

Max duration = 60
Min duration = 1

In [105]:
# Using the new dataframe, update it so that is ONLY has records where
# the tire_size is 26.

shortened_rides = shortened_rides.query('tire_size == 26')

In [106]:
# Finally, produce a count of all records with FEMALE riders
# using the 26-inch wheeled rental bikes for their rentals of
# one hour or less.

new_rides = (shortened_rides.query('user_gender == "female" and tire_size == 26 and duration <= 60'))

print(len(new_rides.index))

0

2. Find the file `more-messy-data.csv` on GitHub and upload it into Google Colab.

Create a new Pandas DataFrame from that data and perform the following steps.

In [130]:
# Write a snippet of code that will display the number of duplicate rows exist in the DF.
df = pd.read_csv("more-messy-data.csv")
count_duplicate = df.duplicated().sum()
print(count_duplicate)

287

In [131]:
# Next, remove all duplicate rows using Python.
df = df.drop_duplicates()

In [110]:
df['petal_width'] = df['petal_width'].astype(float)

ValueError: could not convert string to float: 'gg28'

In [137]:
for i, entry in enumerate(df['petal_width']):
  print(i, entry)

0 0.5
1 0.5
2 1.5
3 1.2
4 1.2
5 2.3
6 1.4
7 2.1
8 3
9 1.9
10 1.3
11 1.9
12 2.6
13 0.4
14 0.7
15 2.6
16 0.9
17 1.8
18 nan
19 0.7
20 1.9
21 0.3
22 0.7
23 2.2
24 0.1
25 1.2
26 2.3
27 2.7
28 2.6
29 nan
30 0.1
31 1.3
32 2.9
33 nan
34 2.2
35 1
36 1.6
37 0.7
38 1.9
39 2.4
40 2
41 1.9
42 2.9
43 2
44 0.6
45 2.9
46 2.2
47 0.8
48 0.3
49 3
50 2.7
51 2.2
52 2.4
53 2.8
54 0.9
55 2.2
56 1.1
57 0.2
58 nan
59 2.4
60 nan
61 1.7
62 2.1
63 0.6
64 1.9
65 nan
66 0.1
67 0.7
68 1.6
69 2.2
70 nan
71 2.8
72 0
73 1.6
74 0.9
75 1.5
76 2.3
77 2.9
78 2.8
79 2.5
80 2.6
81 1.5
82 1.4
83 2.7
84 2.9
85 2.6
86 nan
87 0.3
88 1.6
89 1.9
90 0.5
91 0.2
92 2.3
93 2.5
94 0.5
95 0.7
96 0.1
97 1.5
98 2.6
99 0.1
100 3
101 0.7
102 2
103 2.6
104 1.2
105 2.1
106 0.2
107 0
108 0.8
109 1.7
110 0.3
111 2.7
112 1.1
113 0.3
114 2.4
115 nan
116 nan
117 2.8
118 2.8
119 nan
120 1.3
121 1.5
122 0.7
123 0.9
124 2.1
125 nan
126 0.3
127 2.7
128 2.3
129 2.2
130 0
131 2.3
132 2.8
133 0.4
134 0.8
135 0.1
136 nan
137 0.9
138 2.9
139 1.4
140 0.6
141 0.2
142 0.4
143 2.8
144 nan
145 1.7
146 0.8
147 1.4
148 2.3
149 1.5
150 0.4
151 1.1
152 0.3
153 0.8
154 2.8
155 0
156 2.8
157 2.3
158 2.8
159 1.5
160 0.2
161 nan
162 0.8
163 2.9
164 1.5
165 1.8
166 2.7
167 0.5
168 1.6
169 0.5
170 0.8
171 nan
172 0.5
173 nan
174 1.3
175 2.4
176 1.5
177 1
178 1.3
179 1.5
180 2.4
181 2.5
182 0.3
183 0.2
184 0.7
185 2.2
186 1.3
187 2.8
188 1.1
189 1.4
190 0.7
191 2.5
192 2.4
193 1.5
194 nan
195 1.9
196 2.1
197 1.5
198 1.9
199 0.3
200 2
201 1.2
202 0.5
203 1.7
204 2.4
205 1.8
206 2.3
207 nan
208 nan
209 2.6
210 2.8
211 2.8
212 1.2
213 1.2
214 1.7
215 0.9
216 0.5
217 1.5
218 3
219 0.4
220 0
221 1.1
222 1.7
223 2.1
224 2.4
225 2.6
226 2.4
227 2.2
228 1.8
229 0.7
230 1
231 2.2
232 1.7
233 2
234 2.8
235 2.4
236 2.9
237 nan
238 0.2
239 0.1
240 0.6
241 2.7
242 nan
243 2.8
244 0.5
245 0.3
246 1.9
247 2.5
248 0.1
249 2.4
250 2.7
251 1.9
252 0.9
253 1.4
254 nan
255 2
256 2.9
257 0.6
258 0.5
259 2.6
260 1.1
261 2.9
262 nan
263 0
264 3
265 2.1
266 nan
267 2.5
268 0.1
269 1.8
270 2.6
271 0.6
272 2.5
273 0.6
274 1.2
275 2.2
276 1.1
277 2.4
278 nan
279 nan
280 0.9
281 0.2
282 2.5
283 1.9
284 1.1
285 nan
286 2.7
287 3
288 1
289 1.6
290 2.3
291 0.5
292 2.5
293 1.7
294 2.9
295 0.1
296 1.4
297 2.6
298 0.3
299 2
300 0
301 1.1
302 2.6
303 1.4
304 1.8
305 nan
306 2.4
307 2.8
308 2.8
309 1
310 0.1
311 0.7
312 0.4
313 nan
314 1.9
315 0.9
316 2.7
317 2.4
318 2.3
319 2.6
320 2.4
321 0.4
322 2
323 1.4
324 2.3
325 1.3
326 1.6
327 1.6
328 1.8
329 2.4
330 1
331 0.8
332 1.4
333 2
334 0.2
335 0.5
336 0.8
337 2
338 1.7
339 nan
340 0.1
341 1.9
342 1.4
343 nan
344 nan
345 nan
346 1.1
347 1.7
348 0
349 1.4
350 1.2
351 2.6
352 1.9
353 2.3
354 2.3
355 0.8
356 2.6
357 0.2
358 2.5
359 1.4
360 1
361 2.4
362 1.4
363 nan
364 nan
365 1.3
366 2.3
367 3
368 1.1
369 2.4
370 nan
371 0.6
372 0.6
373 1.3
374 1.4
375 3
376 2.4
377 2.6
378 0.5
379 2
380 2.9
381 1
382 0.1
383 0.7
384 1.7
385 1.7
386 nan
387 2.1
388 2.3
389 0.2
390 2.5
391 2
392 1
393 nan
394 1.4
395 0.3
396 nan
397 0.9
398 2.3
399 2.6
400 1.6
401 0.6
402 0.4
403 0.8
404 1.9
405 0.7
406 2.5
407 1.7
408 0.9
409 0.5
410 0.1
411 2.8
412 nan
413 1
414 2.4
415 2.6
416 1.6
417 1.3
418 2.5
419 2.1
420 0.4
421 2.2
422 0.7
423 nan
424 1.7
425 2.7
426 2.4
427 0.6
428 0.9
429 0.7
430 1.7
431 2.9
432 0.1
433 2.2
434 2.1
435 0.6
436 2.9
437 0.1
438 1.2
439 0.6
440 0.9
441 0.5
442 2.8
443 0.3
444 2.4
445 2
446 1.3
447 2
448 0
449 0.5
450 1
451 1.2
452 2.7
453 2.1
454 2.6
455 0
456 2.4
457 0
458 0.1
459 0.6
460 0.5
461 2.2
462 1.3
463 1
464 2.5
465 2.8
466 2.1
467 2.8
468 0.8
469 1.7
470 1.2
471 2.6
472 2.9
473 nan
474 1.7
475 1.2
476 1.8
477 2
478 2.6
479 1.6
480 2.6
481 1.7
482 1.1
483 1.1
484 1.9
485 2
486 2.6
487 nan
488 2.6
489 0.4
490 0.3
491 0.2
492 0.7
493 0
494 1.3
495 0.6
496 2.4
497 1.1
498 0.6
499 0.5
500 2.3
501 3
502 0.5
503 nan
504 1.1
505 2.5
506 2.8
507 2.1
508 2.5
509 2.6
510 1.7
511 2.3
512 0.6
513 1.3
514 2
515 0.3
516 2.9
517 0.5
518 2.3
519 0.7
520 1.2
521 2.8
522 1.2
523 0.3
524 0.2
525 1.9
526 1.3
527 2
528 2.7
529 1
530 1.5
531 1
532 nan
533 0.6
534 0.3
535 0.4
536 nan
537 2.7
538 0.2
539 0.9
540 1.2
541 0.5
542 1.7
543 1.1
544 2.6
545 1.8
546 2.2
547 1.2
548 2.9
549 0
550 1.7
551 0.3
552 1
553 1
554 1
555 2.9
556 2.8
557 2.7
558 0.2
559 2.2
560 1.2
561 2.5
562 1.8
563 2.2
564 0.4
565 0.2
566 2.6
567 2.9
568 0.4
569 2.4
570 0.5
571 2
572 2.4
573 2.8
574 nan
575 2.1
576 1.1
577 2.2
578 1.5
579 1.5
580 2.5
581 1.2
582 2.9
583 2.7
584 1
585 0.5
586 2.1
587 2
588 1.6
589 1.1
590 0.5
591 1.3
592 1
593 2.4
594 0.6
595 1.1
596 2.8
597 2.8
598 2
599 2
600 1.6
601 2.4
602 2.5
603 2.6
604 0.2
605 2.6
606 0.5
607 1.6
608 1.1
609 2.7
610 0
611 2.7
612 2.4
613 2.4
614 0.9
615 2.1
616 nan
617 2.2
618 1.4
619 1.7
620 0.7
621 0.3
622 2.8
623 2.4
624 nan
625 0.4
626 1.6
627 2.1
628 1.1
629 2.8
630 0.1
631 2.2
632 0.8
633 0.7
634 1.7
635 1.5
636 1.7
637 0.3
638 0.1
639 2.7
640 nan
641 1
642 2.8
643 1.5
644 1.3
645 0.2
646 0.6
647 2.9
648 2.8
649 2.3
650 2.3
651 1.5
652 2.8
653 0.3
654 2.5
655 0.6
656 1.4
657 2.6
658 1.7
659 2.5
660 1.6
661 2.3
662 1.6
663 2.9
664 0
665 0.4
666 0.1
667 nan
668 2.3
669 0.4
670 0.2
671 2.5
672 2.6
673 1.2
674 0
675 1.2
676 1.4
677 1
678 0.3
679 0.6
680 1.7
681 2
682 1.4
683 0.2
684 0.2
685 1.3
686 2.6
687 1.1
688 3
689 nan
690 0
691 1.3
692 2
693 2.7
694 1.1
695 1.4
696 2.4
697 1.3
698 2.2
699 0.6
700 1.7
701 0.6
702 1.8
703 1.9
704 1.7
705 0.9
706 2.8
707 2.4
708 1.6
709 3
710 nan
711 1.5
712 2.5
713 nan
714 1.7
715 0.3
716 2.1
717 0.7
718 nan
719 2.2
720 nan
721 2
722 0.1
723 2
724 2.5
725 nan
726 1.9
727 0
728 2.9
729 2.9
730 2.9
731 1.7
732 0.3
733 2.5
734 0.1
735 0.6
736 0.1
737 0.4
738 1
739 1.7
740 0.5
741 2.4
742 2.8
743 2
744 1.4
745 2.4
746 0.2
747 1.4
748 1
749 0.4
750 1.9
751 1.5
752 2.2
753 2.5
754 2
755 2.9
756 0.8
757 2.7
758 0.6
759 0.7
760 nan
761 1.5
762 2.7
763 2
764 1
765 0
766 2.5
767 0.4
768 2.1
769 0.8
770 2.6
771 1.3
772 3
773 1.2
774 1.7
775 1.2
776 0.2
777 2
778 2.8
779 2.4
780 0.9
781 1.8
782 1.8
783 2.1
784 3
785 3
786 2
787 2.7
788 1.5
789 1.8
790 2.6
791 2.1
792 1.6
793 nan
794 2.2
795 0.7
796 2.8
797 1.3
798 0.9
799 nan
800 1.1
801 0.2
802 0.8
803 2.7
804 2.5
805 0.1
806 0.2
807 1.6
808 2.3
809 0.9
810 0.2
811 nan
812 0.3
813 1.8
814 2.6
815 2.6
816 2.8
817 1.8
818 2.8
819 0.2
820 1.3
821 0.7
822 2.4
823 1.9
824 1.8
825 2.1
826 2.6
827 2.3
828 1.3
829 2.8
830 2.8
831 2.5
832 2.4
833 1.8
834 1.8
835 1
836 1.1
837 2.4
838 0.8
839 1.5
840 nan
841 0.8
842 0.5
843 2.9
844 1.4
845 0.5
846 nan
847 0.7
848 0.3
849 0.1
850 2.5
851 1.1
852 1.5
853 1.3
854 1
855 1.7
856 1.5
857 1.3
858 1
859 2
860 2.7
861 nan
862 2.1
863 2.5
864 2.4
865 0.4
866 nan
867 2.6
868 1.1
869 0.9
870 1.6
871 0.1
872 1.7
873 1.1
874 0.5
875 1.4
876 0.9
877 0
878 0.8
879 0.6
880 2.2
881 1.1
882 2.6
883 2.3
884 0.2
885 1.6
886 0.9
887 0.5
888 2.8
889 0.8
890 1.4
891 0.4
892 1.7
893 0.7
894 1.3
895 2
896 2.2
897 0.7
898 2.3
899 2.5
900 1.7
901 1.9
902 1
903 0.5
904 1.8
905 2.8
906 2.7
907 nan
908 2.2
909 0.7
910 0.7
911 1.3
912 nan
913 2
914 nan
915 0.9
916 nan
917 2.5
918 2.1
919 2.2
920 0.8
921 0.7
922 2.4
923 1.4
924 3
925 0.3
926 1.5
927 1.6
928 0.8
929 0.9
930 2.3
931 nan
932 2.7
933 1.3
934 0.1
935 2.2
936 2.6
937 2.9
938 0.7
939 0.8
940 nan
941 2.4
942 0.5
943 2.6
944 1.9
945 2.2
946 0.9
947 2
948 2
949 2.3
950 1.4
951 1.2
952 2.8
953 2.7
954 nan
955 0.1
956 1.4
957 1.6
958 1.6
959 1.7
960 0.7
961 nan
962 2.2
963 0.4
964 1.3
965 2.6
966 0.3
967 0.7
968 2.5
969 0
970 0.6
971 nan
972 2.5
973 0.6
974 3
975 0.9
976 1.3
977 0.6
978 0.9
979 nan
980 0.3
981 2.3
982 2.8
983 1.8
984 2.9
985 2.1
986 0.5
987 0.6
988 2.9
989 2.8
990 1.2
991 0.3
992 0.2
993 2.7
994 2.1
995 2.5
996 nan
997 1.5
998 3
999 1.7
1000 1.1
1001 nan
1002 nan
1003 nan
1004 0.8
1005 0.3
1006 1.2
1007 1.5
1008 3
1009 0.4
1010 0
1011 1.1
1012 1.7
1013 2.1
1014 2.4
1015 2.6
1016 0.2
1017 2.7
1018 0.7
1019 2.5
1020 1.7
1021 0.9
1022 0.5
1023 0.1
1024 2.8
1025 nan
1026 1

In [140]:
# For the FOUR columns involving sepal and petal length and width, update all NaN
# values with the column mean.

df['sepal_length'].fillna(df['sepal_length'].mean(), inplace=True)
df['sepal_width'].fillna(df['sepal_width'].mean(), inplace=True)
df['petal_length'].fillna(df['petal_length'].mean(), inplace=True)
df['petal_width'] = pd.to_numeric(df['petal_width'])
df['petal_width'].fillna(df['petal_width'].mean(), inplace=True)

In [143]:
# Find any values in the dataframe that are still missing, and delete them.
df.dropna(inplace=True)

In [146]:
# How many different species are there?
count_species = df['species'].nunique()

print(count_species)

10

In [149]:
# Clean up the 'species' variable so that there are exactly three different values.

species_names = ["virginica", "setosa", "Versicolor"]
df = df[df['species'].isin(species_names)]

count_species = df['species'].nunique()
print(count_species)

3

3. Bonus:  Regular expressions

Ordinary (non-vanity) Virginia license plates have the form `ABC1234`, meaning they have three upper case letters followed by four digits.  Write a regular expression that matches any string of this form (and doesn't match anything else).  Test your expression with code to make sure it works.

To figure out out how to do this, start with the sample code below.  The `re` package has various functions related to regular expressions, including for example `match()`, which takes two arguments, first the regular expression and second the test string, and tests to see whether the *beginning* of the `test` string matches the pattern `exp`.

Note that `re.match(exp,test)` does not return a boolean variable, as you might expect (in other words, a match doesn't return `True` and a non-match `False`).  The type of object you get is called `re.Match`, which is a data type special to the `re` package.  (The reason for this is that the object contains more information than just whether there is a match or not.) However, you can turn it into a boolean using `bool()` if you want.

Include the following in the notebook you submit:

 1. A regular expression in a text chunk
 2. One or more code chunks in which you test several strings to verify that your regex is correct.
 3. Make sure you display the results of testing various strings.

 See this [documentation page](https://docs.python.org/3/howto/regex.html#regex-howto) for further help.

In [ ]:
# Sample code for testing whether a string matches a regex

# First import this package for working with regular expressions
import re

# Here is an example.
# Play around with different expressions and test strings to see what happens.
exp = 'ab+'
test = 'aabbbc'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
# print(type(re.match(exp,test)))

# uncomment this line if you want
# print(bool(re.match(exp,test)))